const items = [
    {
       id:'001',
        Image: 'images/cake1.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
       
    },
    {
       id:'002',
        Image: 'images/cake2.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
    },
    {
       id:'003',
        Image: 'images/cake3.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
    },
    {
       id:'004',
        Image: 'images/cake4.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
    },
    {
       id:'005',
        Image: 'images/cake5.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
    },
    {
       id:'006',
        Image: 'images/cake6.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
    },
    {
       id:'007',
        Image: 'images/cake7.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
    },
    {
       id:'008',
        Image: 'images/cake8.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
    },
    {
       id:'009',
        Image: 'images/cake9.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
    },
    {
       id:'010',
        Image: 'images/cake10.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
    },
    {
       id:'011',
        Image: 'images/cake10.png',
        items_name: 'Chocolate',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa adipisci reiciendis assumenda.',
        original_price: 300 ,
         current_price: 250 ,
         discount_persent: 10 ,
    },
  

];